import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { add } from "bundler-test";
import { Button } from "bunbler-test-components";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <p>{add(5, 2)}</p>
        <Button>aa</Button>
      </main>
    </>
  );
}
