import Head from "next/head";
import { add } from "bundler-test";
// import { Button } from "bunbler-test-components";
import { Button } from "hsh-components-tailwind-green";
import { cls } from "hsh-utils-string";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex w-ull justify-center flex-col">
          <p className={cls("flex justify-center", "w-full h-[600px]")}>
            {add(5, 2)}
          </p>
          <Button className={cls("")}>aa</Button>
        </div>
      </main>
    </>
  );
}
